language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
  - mv .travis-gitignore .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "dist"
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    tags: true